###
GET {{url}}/dubbo/getCityName?cityName=taylor
Cache-Control: no-cache

###
GET {{url}}/dubbo/getUser
Cache-Control: no-cache



//////////////////////////////////////////- interview -//////////////////////////////////////////
###
GET {{url}}/non/testNonNull?name=" "&id=1&size=a,b,c,d,f,g
Accept: */*
Cache-Control: no-cache

###
POST {{url}}/non/myCheck
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "cid": 1,
  "name": "北京",
  "beginTime": "2019-10-10",
  "overTime": "2019-10-10"

}

###
GET {{url}}/non/customeStarter
Accept: */*
Cache-Control: no-cache

###

###
GET {{url}}/encry/getUsers
Accept: */*
Cache-Control: no-cache

###
### 获取加密串
GET {{url}}/encry/encryptInfo?key=68A61C323A3452544C4AEF6296D8BD95A
Accept: */*
Cache-Control: no-cache

###### 动态数据源

# docker run -d -v /data:/data --name magic-interview-8091 -p 8091:8091 magic-interview:1.1-8091

# docker run -d --name es  -v /usr/local/docker/es/config:/usr/share/elasticsearch/config -p 9200:9200 -p 9300:9300 -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -e "discovery.type=single-node" 8b4495052160

#docker run -d --name es -p 9200:9200 -p 9300:9300 -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -e "discovery.type=single-node" 8b4495052160

#docker pull docker.elastic.co/kibana/kibana:5.6.16

#docker run --name kibana -p 5601:5601 -d 镜像id
GET {{url}}/dynamic/getList
Accept: */*
Cache-Control: no-cache

###缓存问题
###
GET {{url}}/ques/breakdown
Accept: */*
Cache-Control: no-cache

### scan 0 match test* count 5
### &value=1
GET {{url}}/ques/redis/del?key=record:list
Accept: */*
Cache-Control: no-cache

###

###
GET {{url}}/lock/redisson
Accept: */*
Cache-Control: no-cache

###
###
GET {{url}}/lock/noLock
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/lock/reSet/50
Accept: */*
Cache-Control: no-cache

###
###
GET {{url}}/parameter/anno
Accept: */*
Cache-Control: no-cache
sessionId: 2
###