###
GET {{url}}/dubbo/getCityName?cityName=taylor
Cache-Control: no-cache

###
GET {{url}}/dubbo/getUser
Cache-Control: no-cache



//////////////////////////////////////////- interview -//////////////////////////////////////////
###
GET {{url}}/non/testNonNull/123.1?name=''&id=2&size=a,b,c,d,f
Accept: */*
Cache-Control: no-cache

###
POST {{url}}/non/list
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

[
{"cid": 1,
  "name": "北京",
  "beginTime": "2019-10-10",
  "overTime": "2019-10-11",
  "job": [
    {
      "jobId": 2,
      "jobName": "上海"
    },
    {
      "jobId": 1,
      "jobName": "上下"
    }
  ]},
  {"cid": 1,
  "name": "北京",
  "beginTime": "2019-10-10",
  "overTime": "2019-10-11",
  "job": [
    {
      "jobId": 2,
      "jobName": "上海"
    },
    {
      "jobId": 3,
      "jobName": "上xia"
    }
  ]}
]


###
POST {{url}}/non/myCheck
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "cid": 1,
  "name": "北hai",
  "beginTime": "2019-10-10",
  "overTime": "2019-10-10",
  "job": [
    {
      "jobId": 2,
      "jobName": "上海"
    },
    {
      "jobId": 3,
      "jobName": "上"
    }
  ]

}

###
GET {{url}}/non/customeStarter
Accept: */*
Cache-Control: no-cache

###

###
GET {{url}}/encry/getUsers
Accept: */*
Cache-Control: no-cache

###
### 获取加密串
GET {{url}}/encry/encryptInfo?key=182
Accept: */*
Cache-Control: no-cache

###### 动态数据源

# docker run -d -v /data:/data --name magic-interview-8091 -p 8091:8091 magic-interview:1.1-8091

# docker run -d --name es  -v /usr/local/docker/es/config:/usr/share/elasticsearch/config -p 9200:9200 -p 9300:9300 -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -e "discovery.type=single-node" 8b4495052160

#docker run -d --name es -p 9200:9200 -p 9300:9300 -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -e "discovery.type=single-node" 8b4495052160

#docker pull docker.elastic.co/kibana/kibana:5.6.16

#docker run --name kibana -p 5601:5601 -d 镜像id

# docker pull rabbitmq:management
# docker run -d --hostname my-rabbit --name rabbit -e RABBITMQ_DEFAULT_USER=taylor -e RABBITMQ_DEFAULT_PASS=182 -p 15672:15672 -p 5672:5672 fe3459a432a4

GET {{url}}/dynamic/getList
Accept: */*
Cache-Control: no-cache

###缓存问题
###
GET {{url}}/ques/breakdown
Accept: */*
Cache-Control: no-cache

### scan 0 match test* count 5
### &value=1
GET {{url}}/ques/redis/del?key=record:list
Accept: */*
Cache-Control: no-cache

###

###
GET {{url}}/lock/redisson
Accept: */*
Cache-Control: no-cache

###
###
GET {{url}}/lock/noLock
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/lock/reSet/50
Accept: */*
Cache-Control: no-cache

###
###
GET {{url}}/parameter/anno
Accept: */*
Cache-Control: no-cache
sessionId: 2
###

###
GET {{url}}/event/register
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=utf-8

{
"username": "ariana",
  "pwd": "123"
}

###
###
GET {{url}}/mq/send
Accept: */*
Cache-Control: no-cache

###测试：
# 发送Exchange 失败
# 路由queue 失败
# 不手动确认
# 消费幂等
# 消费异常，basicNack
# ConfirmCallback没有被执行



###
GET {{url}}/httpClient/restTemplate
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/jwt/login/1?uid=123456
Accept: application/json
Cache-Control: no-cache
api-version: 2
#code:

> {% client.global.set("token", response.body.data) %}

###
GET {{url}}/jwt/getInfo
Accept: */*
Cache-Control: no-cache
Authorization: Bearer {{token}}
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI0NTY3ODkiLCJ2ZXJzaW9uIjoxMiwiZXhwIjoxNTk5NzA2MjE2fQ==.fgJYmNbwvsJdLahZ9mUYjDSe-B0Dls1bFIg-99DOoPA


###
GET {{url}}/order/getResult
Accept: application/json
Cache-Control: no-cache