###
GET {{url}}/dubbo/getCityName?cityName=taylor
Cache-Control: no-cache

###
GET {{url}}/dubbo/getUser
Cache-Control: no-cache

###
GET {{url}}/non/testNonNull?name=" "&id=1&size=a,b,c,d,f,g
Accept: */*
Cache-Control: no-cache

###
POST {{url}}/non/myCheck
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "cid": 1,
  "name": "北京",
  "beginTime": "2019-10-10",
  "overTime": "2019-10-10"

}

###